---
title: 'Introduction to Software Product Management'
author: '`r if(knitr::is_html_output()) {"&#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Anderson H Uyekita"} else {NULL}`'
output:
  github_document: default
params:
  author: 'Anderson H Uyekita'
  course: 'Introduction to Software Product Management'
  course_url: 'https://www.coursera.org/learn/introduction-to-software-product-management'
  specialization: 'Software Product Management Specialization'
  specialization_url: 'https://www.coursera.org/specializations/product-management'
  instructor: 'Kenny Wong'
  course_start: !r lubridate::ymd('2022/06/29')
  course_finish: !r lubridate::today(tzone = "America/Sao_Paulo")
  certificate_url: './'
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE)
library(rmarkdown)
library(lubridate)
```

`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Author: %s", params$author)}`
`r sprintf(fmt = "* &#x1f4da; Specialization: [%s](%s){target='_blank' rel='noopener'}", params$specialization, params$specialization_url)`
`r sprintf(fmt = "* &#x1f4d6; Course: [%s](%s){target='_blank' rel='noopener'}", params$course, params$course_url)`
    `r sprintf(fmt = "* &#x1F9D1;&#x200d;&#x1F3EB; Instructor: %s", params$instructor)`
    `r sprintf(fmt = "* &#x1F6A6; Start: %s", format(params$course_start, "%A, %d %B %Y"))`
    `r sprintf(fmt = "* &#x1F3C1; Finish: %s", format(params$course_finish, "%A, %d %B %Y"))`
`r if(params$certificate_url != "./") {sprintf(fmt = "* &#x1F393; [Certificate](%s)", params$certificate_url)}`

--------------------------------------------------------------------------------

#### Assignments & Deliverables

* [&#x1F4DD; Quiz 1](./Week 1/quiz-1_introduction-to-software-product-management.md)
* [&#x1F4DD; Quiz 2](./Week 2/quiz-2_introduction-to-software-product-management.md)

#### Class Notes

* [&#x1F4C6; Week 1](./Week 1)
* [&#x1F4C6; Week 2](./Week 2)
* [&#x1F4D1; Course Textbook Notes](./book)

#### Course Description

This course highlights the importance and role of software product management. It also provides an overview of the specialization, as well as its goals, structure, and expectations. The course explains the value of process, requirements, planning, and monitoring in producing better software.


#### Course Syllabus

* Lesson 1: Better Software
* Lesson 2: Why Software Product Management?
* Lesson 3: The Role of a Software Product Manager
* Lesson 4: Specialization Overview
* Lesson 5: Project Success, Why Agile?
* Lesson 6: Agile Manifesto
* Lesson 7: Why Process?
* Lesson 8: Why Requirements?
* Lesson 9: Why Planning?
* Lesson 10: Why Monitoring?

#### Course Textbook

The book [&#x1F4D4; NA](./book/na.pdf) covers the lecture material in this course.

#### Course Projects




