---
title: '`Quiz 1` Introduction to Software Product Management'
author: '`r if(knitr::is_html_output()) {"&#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Anderson H Uyekita"} else {NULL}`'
output:
  github_document: default
  html_document:
    self_contained: yes
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
      smooth_scroll: true
params:
  author: 'Anderson H Uyekita'
  course: 'Introduction to Software Product Management'
  course_url: 'https://www.coursera.org/learn/introduction-to-software-product-management'
  specialization: 'Software Product Management Specialization'
  specialization_url: 'https://www.coursera.org/specializations/product-management'
  instructor: 'Kenny Wong'
  course_start: !r lubridate::ymd('2022/06/30', tz = "America/Sao_Paulo")
  course_finish: !r lubridate::ymd('2022/06/30', tz = "America/Sao_Paulo")
  week: ' Week 1'
always_allow_html: true
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE)
library(rmarkdown)
library(lubridate)
```

`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Author: %s", params$author)}`
`r sprintf(fmt = "* &#x1f4da; Specialization: [%s](%s){target='_blank' rel='noopener'}", params$specialization, params$specialization_url)`
`r sprintf(fmt = "* &#x1f4d6; Course: [%s](%s){target='_blank' rel='noopener'}", params$course, params$course_url)`
    `r sprintf(fmt = "* &#x1F9D1;&#x200d;&#x1F3EB; Instructor: %s", params$instructor)`
`r sprintf(fmt = "* &#x1F4C6; %s", params$week)`
    `r sprintf(fmt = "* &#x1F6A6; Start: %s", format(params$course_start, "%A, %d %B %Y"))`
    `r sprintf(fmt = "* &#x1F3C1; Finish: %s", format(params$course_finish, "%A, %d %B %Y"))`
`r if(!knitr::is_html_output()) {"* &#x1F30E; Rpubs: [Interactive Document](https://rpubs.com/AndersonUyekita/quiz-1_introduction-to-software-product-management)"}else{"* &#x1F4E6; Github Repository: [Static Document](https://github.com/AndersonUyekita/introduction-to-software-product-management/blob/main/Week%201/quiz-1_introduction-to-software-product-management.md){target='_blank' rel='noopener'}"}`

--------------------------------------------------------------------------------

I have found the answers in the [Course Notes.](https://github.com/AndersonUyekita/introduction-to-software-product-management/blob/main/resources/c1-course-notes-introduction-to-software-product-management.pdf)

## Question 1

What are examples of desirable characteristics that effective software product management can help to achieve?

- [x] having regular client demos; meeting client needs; having clear project progress
- [ ] a satisfied client; having regular client demos; client writes automated tests
- [ ] the client specifies requirements; demo is delivered at the end; satisfied developers
- [ ] a satisfied client; the project is on time; lots of overtime hours for developers

**Answer**
Based on first viewpoint:

> Developers can conduct **reviews and tests** to ensure the requirements, design, and implementation line up and do not have defects. That is, the software product is verified.

Based on second viewpoint:

> One viewpoint aims to provide the right software product for **the clients. That is, it meets their needs**, solves their problem, and they are happy with it.

Based on third viewpoint:

> These practices ease communication and feedback, **so that everyone is clear on the next steps**. That is, the project is managed.

## Question 2

As a software product manager, you could be interacting with many business units, such as the executive, marketing, and support. Day to day, however, you mostly focus on representing the needs of two parties, _____ and _____.

- [x] client
- [x] development team
- [ ] CEO
- [ ] end-user

**Answer**

> A software product manager needs a unique set of skills to assess whether the product is meeting **client** expectations, and to work with a **development team** to solve the client’s problems

## Question 3

When we have the software product done right, we say the software product is ____.

- [ ] validated
- [ ] certified
- [x] verified

**Answer**

* Managed: the software project itself managed right ( The idea is to adopt just enough process and suitable practices to organize the work of everyone involved).
* Verified: **the software product done right** (The software implementation conforms to a specified design, and in turn, the design satisfies a stated set of requirements). Also, Developers can conduct reviews and tests to ensure the requirements, design, and implementation line up and do not have defects.
* Validated: the right software product for the clients (it meets their needs, solves their problem, and they are happy with it)


## Question 4

In the four foundational courses, what are the next two courses after the introduction that are the basis for the “planning” course and signified by the legs of an inukshuk?

- [ ] Reviews and Metrics for Client Needs
- [ ] Agile Planning for Software Products
- [x] Software Processes and Agile Practices
- [x] Client Needs and Software Requirements

**Answer**

The foundation “legs” of our specialization structure are the first two courses:

1. Software Process and Agile Practices
2. Client Needs and Software Requirements
3. Agile Planning for Software Products
4. Reviews and Metrics for Software Improvement.